apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: dnd-forum
spec:
  containers:
  - name: psql
    image: postgres:17
    env:
    - name: POSTGRES_HOST
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: db_host
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: db_name
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: db_user
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: db_password
    command: ["sleep", "3600"]

