# rds-credentials-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dnd-forum
type: Opaque
data: 
  POSTGRES_HOST: ZG5kLWZvcnVtLXBvc3RncmVzLmN5b3FvdWFzcGNyYi51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20K
  POSTGRES_DB: RE5EX3VzZXIK 
  POSTGRES_PASSWORD: Vm9sZ2EjNTEK
  POSTGRES_USER: RE5EX2ZvcnVtCg==

